// console.log("Hello typescript");     
// import variables from "./generics/variables";
// import specialTypes from "./generics/special types";
// import objectArraysTuples from "./generics/object arrays tuples";
// import typeAlliances from "./generics/type alliances";
// import myInterface from "./generics/interfaces";
// import unionIntersection from "./generics/union intersection";
// import myfunctions from "./generics/functions";
// import callbacks from "./generics/callbacks";
import myPromises from "./generics/promises";
myPromises();
// callbacks();
// myfunctions();
// unionIntersection();
// myInterface();
// typeAlliances();
// objectArraysTuples();
// specialTypes();
// variables();