// console.log("Hello typescript");     
import variables from "./variables";
import specialTypes from "./special types";
import objectArraysTuples from "./object arrays tuples";
import typeAlliances from "./type alliances";
import myInterface from "./interfaces";
import unionIntersection from "./union intersection";
import myfunctions from "./functions";
import callbacks from "./callbacks";
import myPromises from "./promises";
import myGenerics from "./generics/genericFunctions";
import genericTypes from "./generics/genericTypes";
import classes from "./OOP/Classes";
import accessModifiers from "./OOP/accessModifiers";
import inheritance from "./OOP/inheritance";
import polymorphism from "./OOP/polymorphism";
import encapsulation from "./OOP/encapsulation";
encapsulation();
// polymorphism();
// inheritance();
// accessModifiers();
// classes();
// genericTypes();
// myGenerics();
// myPromises();
// callbacks();
// myfunctions();
// unionIntersection();
// myInterface();
// typeAlliances();
// objectArraysTuples();
// specialTypes();
// variables();