// console.log("Hello typescript");     
// import variables from "./variables";
// import specialTypes from "./special types";
// import objectArraysTuples from "./object arrays tuples";
// import typeAlliances from "./type alliances";
import myInterface from "./interfaces";
// import unionIntersection from "./union intersection";
// import myfunctions from "./functions";
// import callbacks from "./callbacks";
// import myPromises from "./promises";
// myPromises();
// callbacks();
// myfunctions();
// unionIntersection();
myInterface();
// typeAlliances();
// objectArraysTuples();
// specialTypes();
// variables();